service: slack-listener 

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  profile: cloudformation_role
  role: arn:aws:iam::844297601570:role/SlackLambdaRole

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  
functions:
  wfh-listener:
    handler: handlers/wfh-listener.index
    events:
      - http:
          path: /wfh-listener
          method: post
    calendar:
    handler: handler.index
    events:
      - http: get /calendar