service: slack-listener 

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  profile: cloudformation_role
  role: arn:aws:iam::844297601570:role/SlackLambdaRole

plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  
functions:
  wfh-listener:
    handler: handlers/wfh-listener.index
    events:
      - http:
          path: /wfh-listener
          method: post
  auth:
    handler: handlers/auth
    environment: 
      SLACK_API_KEY: ${file(./serverless.env.yml):dev.SLACK_API_KEY}
      APP_ID: ${file(./serverless.env.yml):dev.APP_ID}
      CLIENT_ID: ${file(./serverless.env.yml):dev.CLIENT_ID}
      CLIENT_SECRET: ${file(./serverless.env.yml):dev.CLIENT_SECRET}
      SIGNING_SECRET: ${file(./serverless.env.yml):dev.SIGNING_SECRET}
      VERIFICATION_TOKEN: ${file(./serverless.env.yml):dev.VERIFICATION_TOKEN}
